# Generated by Django 4.2.6 on 2023-10-09 12:09

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import products.valid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_remove_customeruserprofile_is_staff_and_more'),
        ('products', '0002_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.category_image_path, validators=[products.valid.valid_image_exstension]),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avaible', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_top', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countInStock', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('whislist', models.ManyToManyField(to='customers.customeruserprofile')),
            ],
        ),
    ]
