# Generated by Django 4.2.6 on 2023-10-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image3_remove_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='font-awesome icon ekle örnek fa-home ', max_length=200, null=True, verbose_name='Font Awesome Icon'),
        ),
    ]
