# Generated by Django 4.2.6 on 2023-10-11 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menuicon',
            field=models.CharField(default=django.utils.timezone.now, help_text='Font Awesome sitesinden alabilirsin icon örnek kullanım : fa-regular fa-circle-xmark   fa-solid fa-circle-xmark', max_length=200, verbose_name='Font Awesome icon'),
            preserve_default=False,
        ),
    ]
