# Generated by Django 4.2.6 on 2023-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_menuicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='menuicon',
            field=models.CharField(blank=True, help_text='Font Awesome sitesinden alabilirsin icon örnek kullanım : fa-regular fa-circle-xmark   fa-solid fa-circle-xmark', max_length=200, null=True, verbose_name='Font Awesome icon'),
        ),
    ]
