# Generated by Django 4.0.2 on 2023-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
