# Generated by Django 4.2.6 on 2023-10-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='is_superuser',
        ),
    ]
