# Generated by Django 4.2.6 on 2023-10-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('product_count', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
