# Generated by Django 4.2.6 on 2023-10-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='is_superuser',
        ),
    ]
